### ISSUE TITLE
Certificate error while deploying git-controller to the local kind custer

### ISSUE THREAD

**Issue by mohammad-ammar14** [open-component-model/git-controller#67]
I have generated certificates it is available in the project folder before deploying to cluster. Still I am getting error 
`Unable to attach or mount volumes: unmounted volumes=[certificates], unattached volumes=[certificates kube-api-access-7v2mh]: timed out waiting for the condition`

I also tried using tilt it is running in my cluster.
<img width="1512" alt="Screenshot 2023-09-26 at 2 06 41 PM" src="https://github.com/open-component-model/git-controller/assets/120632768/53502a01-f927-4847-8cca-9efdc0e3a333">

**Comment by Skarlso** [comment]
We figured this out as being a bug in the MPAS CLI deploying an older version.

Closing this as Mohammad showed me a working deployment in the end.
