### ISSUE TITLE
Documentation for how to attach certificate to git-controller pod 

### ISSUE THREAD

**Issue by mohammad-ammar14** [open-component-model/git-controller#68]
Just wanted to proposed improvement in documentation. Please add few steps how to attached certificate or how a tilt can be use to volume attached in git controller pod.

**Comment by robertwol** [comment]
@mohammad-ammar14 since you talk to @Skarlso, I wonder if you could come with proposal PR?

**Comment by Skarlso** [comment]
Actually, the attaching is already done in a patch through kustomize. All you need is the certificate secret to exist in the cluster.

**Comment by Skarlso** [comment]
This is done.
